config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"
  resources :users do
    get "users/follows" => "users#follows"
    get "users/followers" => "users#followers"
    resource :relationships, only: [:create, :destroy]
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower_do, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :follower_user, through: :follower_do, source: :followed

  has_many :followed_do, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_user, through: :followed_do, source: :follower

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def self.looks(matches, words)
    if matches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif matches == "left_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif matches == "right_match"
      @user = User.where("name LIKE ?", "%#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

  def follow_by?(user)
    followed_do.find_by(follower_id: user.id).present?
  end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end


  def show
    @user = User.find(params[:id])
    @book = Book.new

    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @roomid = cu.room_id
          end
        end
      end
      if @is_room != true
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "successfully"
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:user_id])
    @users = user.follower_user
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followed_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.erb
<div class="col-md-3">
  <h1>User info</h1>
  <%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name%></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to "#{user.follower_do.count}", user_users_follows_path(user)  %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to "#{user.followed_do.count}", user_users_followers_path(user) %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <% if current_user != user %>
      <% if user.follow_by?(current_user) %>
        <td><%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %></td>
        <% if current_user.follow_by?(user) %>
          <% if is_room == true %>
            <td class="user-show-room">
              <%= link_to "チャットへ", room_path(roomid), class: "btn btn-primary" %>
            </td>
          <% else %>
            <%= form_with model:room, local:true do |f| %>
              <%= fields_for entry, local:true do |e| %>
                <%= e.hidden_field :user_id, value: user.id %>
              <% end %>
              <%= f.submit "チャットを始める", class:"btn btn-primary user-show-chat"%>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %></td>
      <% end %>
    <% elsif current_user == user %>
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do  %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model:book, local: true do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :opinion %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit "Create Book", class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div id="error_explanation">
        <% if @user.errors.any? %>
          <p><%= @user.errors.full_messages.count %>件のerror</p>
          <% @user.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        <% end %>
      </div>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Image %>
          <%= f.attachment_field :profile_image %>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
 <h2>Follower Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.follower_do.count %></td>
              <td>フォロワー数：<%= user.followed_do.count %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

app/views/users/follows.html.erb
 <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.follower_do.count %></td>
              <td>フォロワー数：<%= user.followed_do.count %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
              </td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.follower_do.count %></td>
              <td>フォロワー数：<%= user.followed_do.count %></td>
              <% if current_user != user %>
                <% if user.follow_by?(current_user) %>
                  <td><%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></td>
                <% else %>
                  <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
                <% end %>
              <% else %>
                <td></td>
              <% end %>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book, is_room: @is_room, roomid: @roomid, room: @room, entry: @entry %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @user.books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td><%=link_to "#{book.title}", book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td>コメント数：<%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>