config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"
  resources :users do
    get "users/follows" => "users#follows"
    get "users/followers" => "users#followers"
    resource :relationships, only: [:create, :destroy]
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  is_impressionable counter_cache: true

  def self.looks(matches, words)
    if matches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif matches == "left_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    elsif matches == "right_match"
      @book = Book.where("title LIKE ?", "%#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}%")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def week_time
    
    Favorite.where(created_at: from...to).count
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower_do, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :follower_user, through: :follower_do, source: :followed

  has_many :followed_do, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_user, through: :followed_do, source: :follower

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def self.looks(matches, words)
    if matches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif matches == "left_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif matches == "right_match"
      @user = User.where("name LIKE ?", "%#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

  def follow_by?(user)
    followed_do.find_by(follower_id: user.id).present?
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  impressionist :actions=> [:show]

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    from  = Time.current.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @books = Book.left_joins(:favorites).sort {|a, b| b.favorites.where(favorites: {created_at: [from...to]}).size <=> a.favorites.where(favorites: {created_at: [from...to]}).size }
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "successfully"
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index

    end
  end

  def show
    @book_show = Book.find(params[:id])
    @user = User.find(@book_show.user.id)
    @book = Book.new
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if  @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "successfully"
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(entry_params)
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      @entries.each do |entry|
        if entry != current_user.id
          @user = User.find_by(id: entry.id)
        end
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def entry_params
      params.require(:entry).permit(:room_id, :user_id).merge(room_id: @room.id)
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end


  def show
    @user = User.find(params[:id])
    @book = Book.new

    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @roomid = cu.room_id
          end
        end
      end
      if @is_room != true
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "successfully"
    else
      render :edit
    end
  end

  def follows
    user = User.find(params[:user_id])
    @users = user.follower_user
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followed_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_comment.html.erb
<% book.book_comments.each do |book_comment| %>
                <div>
                    <%= link_to user_path(book_comment.user.id) do %>
                    <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %><br>
                    <%= book_comment.user.name %>
                    <% end %>
                    <%= book_comment.comment %>
                    <% if book_comment.user_id == current_user.id %>
                        <%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, class: "btn btn-danger btn-sm", remote: true %><br>
                    <% end %>
                </div>
            <% end %>
            <%= form_with(model:[book, comment]) do |f| %>
                <%= f.text_area :comment, class: "col-12 mt-3" %>
                <%= f.submit "送信" %>
            <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <div id="error_explanation">
        <% if @book.errors.any? %>
          <p><%= @book.errors.full_messages.count %>件のerror</p>
          <% @book.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        <% end %>
      </div>
      <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <p><%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %></p>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <p><%= @book.errors.full_messages.count %>件のerror</p>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/sidebar', user: @user, book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td><%= link_to "#{book.title}", book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td id="favorite-button-<%= book.id %>">
                <%= render 'favorites/favorite', book: book  %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
              <td>閲覧数：<%= book.impressions_count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
    <div class="row">
        <%= render 'users/sidebar', user: @user, book: @book %>
        <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            <%= link_to user_path(@book_show.user.id) do %>
                                <%= attachment_image_tag @book_show.user, :profile_image, :fill, 40, 40, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %><br>
                                <%= @book_show.user.name %>
                            <% end %>
                        </td>
                        <td>
                            <%= link_to book_path(@book_show.id) do %>
                                <%= @book_show.title %>
                            <% end %>
                        </td>
                        <td><%= @book_show.body %></td>
                        <td id="favorite-button-<%= @book_show.id %>">
                            <%= render 'favorites/favorite', book: @book_show  %>
                          </td>
                        <% if @book_show.user_id == current_user.id %>
                            <td><%= link_to "Edit", edit_book_path(@book_show.id), class: "btn btn-sm btn-success" %></td>
                            <td><%= link_to "Destroy", book_path(@book_show.id), method: :delete, data: { confirm: "本当に削除しますか。" }, class: "btn btn-sm btn-danger" %></td>
                        <% end %>
                        <td>コメント数：<%= @book_show.book_comments.count %></td>
                        <td>閲覧数：<%= @book_show.impressionist_count %></td>
                    </tr>
                </tbody>
            </table>
            <div id="book_comment">
                <%= render "books/comment", book: @book_show, comment: @book_comment %>
            </div>
        </div>
    </div>
</div>

app/views/rooms/show.html.erb
<h3><%= link_to "ユーザー一覧に戻る", users_path %></h3>
<h2><%= @user.name %>さんとのチャット</h2>
  <div class="col-md-3">
  <% if @messages.present? %>
    <% @messages.each do |message| %>
      <% if message.room.user_id == current_user.id %>
        <div class="message">
         <p style="text-align: left;"><%= message.text %></p>
        </div>
      <% else %>
        <div class="message-you">
          <p style="text-align: right;"><%= message.text %></p>
        </div>
      <% end %>
    <% end %>
  <% end %>
   <%= form_with model:@message do |f| %>
    <%= f.text_field :text %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <%= f.submit "送信", class:"btn btn-success" %>
  <% end %>
</div>