config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"
  resources :users do
    get "users/follows" => "users#follows"
    get "users/followers" => "users#followers"
    resource :relationships, only: [:create, :destroy]
  end
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  is_impressionable counter_cache: true

  def self.looks(matches, words)
    if matches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif matches == "left_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    elsif matches == "right_match"
      @book = Book.where("title LIKE ?", "%#{words}")
    else
      @book = Book.where("title LIKE ?", "%#{words}%")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def week_time
    
    Favorite.where(created_at: from...to).count
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower_do, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :follower_user, through: :follower_do, source: :followed

  has_many :followed_do, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_user, through: :followed_do, source: :follower

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def self.looks(matches, words)
    if matches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif matches == "left_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif matches == "right_match"
      @user = User.where("name LIKE ?", "%#{words}")
    else
      @user = User.where("name LIKE ?", "%#{words}%")
    end
  end

  def follow_by?(user)
    followed_do.find_by(follower_id: user.id).present?
  end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  impressionist :actions=> [:show]

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    from  = Time.current.at_beginning_of_day
    to = (from + 6.day).at_end_of_day
    @books = Book.left_joins(:favorites).sort {|a, b| b.favorites.where(favorites: {created_at: [from...to]}).size <=> a.favorites.where(favorites: {created_at: [from...to]}).size }
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "successfully"
    else
      @books = Book.all
      @user = User.find(current_user.id)
      render :index

    end
  end

  def show
    @book_show = Book.find(params[:id])
    @user = User.find(@book_show.user.id)
    @book = Book.new
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if  @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "successfully"
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(entry_params)
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      @entries.each do |entry|
        if entry != current_user.id
          @user = User.find_by(id: entry.id)
        end
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def entry_params
      params.require(:entry).permit(:room_id, :user_id).merge(room_id: @room.id)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
      <%= link_to "Bookers", root_path %>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Home", user_path(current_user.id), class: "fas fa-home" %>
          </li>

          <li class="nav-item">
            <%= link_to "Users", users_path, class: "fas fa-users" %>
          </li>

          <li class="nav-item">
            <%= link_to "Books", books_path, class: "fas fa-book-open" %>
          </li>

          <li class="nav-item">
            <%= link_to "logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "fas fa-home" %>
          </li>

          <li class="nav-item">
            <%= link_to "About", home_about_path, class: "fas fa-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "sign up", new_user_registration_path, class: "fas fa-user-plus" %>
          </li>

          <li class="nav-item">
            <%= link_to "login", new_user_session_path, class: "fas fa-sign-in-alt" %>
          </li>
        <% end %>
      </ul>
      </div>
    </nav>

    <div class="Notification">
      <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: key %>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <%= form_with url: searches_search_path, method: :get, local: :true do |f| %>
      <div class="search">
        <%= f.text_field :word %>
        <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
        <%= f.select :match, options_for_select([["完全一致", "perfect_match"], ["部分一致", "partial_match"], ["前方一致", "left_match"], ["後方一致", "right_match"]]) %>
        <%= f.submit "検索" %>
        </div>
      <% end %>
    <% end %>

        <%= yield %>
    <footer>
      <div class="container mt-5">
          <div class="row">
              <div class="mx-auto">
                 CopyRight Infratop.inc
              </div>
          </div>
      </div>
    </footer>
  </body>
</html>